FROM apache/druid:29.0.1

WORKDIR /opt/druid

USER druid

WORKDIR /opt/druid/extensions/

COPY target/*.tar.gz extension.tar.gz
RUN tar xvfz extension.tar.gz && rm extension.tar.gz

WORKDIR /opt/druid
